### ISSUE TITLE
[BUG] Sprite preview...

### ISSUE THREAD

**Issue by XeonG** [Heymity/MolecularLibCore#2]
Unity 2023.1.b9

Caused by this addon.. was working fine in previous version (few months ago haven't worked on the project in a while was just testing in new unity version).. took a while to track it down to this asset bit annoying.. but anyway
![Unity_rJRDZhv7ZD](https://user-images.githubusercontent.com/1556183/227675202-fc830604-e75e-49ed-927c-107daa797b43.png)

**Comment by Heymity** [comment]
I will have a look on it, for now in the docs of the MolecularLib there is guide on how to disable this custom drawer on the Sprite Drawer section (if I am not mistaken its the last section)

Just so I can try to replicate it better, you are using a Sprite inside a class/struct, that has a property drawer, inside a List of such class/struct right?
